---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: podman
platforms:
  - name: "hostname-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: fedora:38
    # image: ubi9/ubi-init:latest
    dockerfile: ../common/Dockerfile.j2
    # registry:
    #   url: registry.access.redhat.com
    privileged: True
    command: "/sbin/init"
    systemd: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    # network: "firewalld_network"
    # subnet: '10.3.1.0/24'
    dns_servers:
      - 8.8.8.8
#    capabilities:
#      - SYS_ADMIN
#      - CAP_SYS_TIME
#    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes
verifier:
  name: ansible
