---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Show virtualization type
      debug:
        var: ansible_facts.virtualization_type
  roles:
    - role: robertdebock.bootstrap
